# -*- coding: utf-8 -*-
"""etl_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YFwNmbb6mdPndAfj4n13EckyN6AR44zG

Import
"""

from google.colab import files
uploaded = files.upload()

"""List Directory"""

import os
os.listdir()

"""# EXTRACT"""

import pandas as pd

customers = pd.read_csv('customers.csv')
products  = pd.read_csv('products.csv')
sales     = pd.read_csv('sales.csv')
stores    = pd.read_csv('stores.csv')
staff     = pd.read_csv('staff.csv')

customers.info()
products.info()
sales.info()
stores.info()
staff.info()

"""# TRANSFORM

Clean + Standardize
"""

for df in [customers, products, sales, stores, staff]:
    df.columns = df.columns.str.lower()
    df.drop_duplicates(inplace=True)

"""Handle Missing Values"""

customers.dropna(inplace=True)
products.dropna(inplace=True)
sales.dropna(inplace=True)
stores.dropna(inplace=True)
staff.dropna(inplace=True)

"""Data Type COnversion"""

sales['saledate'] = pd.to_datetime(sales['saledate'])
products['price'] = products['price'].astype(float)
sales['quantity'] = sales['quantity'].astype(int)

"""Create Fact Metric"""

sales = sales.merge(products[['productid','price']], on='productid', how='left')
sales['totalsales'] = sales['quantity'] * sales['price']

"""Redefine Fact Table"""

fact_sales = sales[[
    'saleid',
    'productid',
    'customerid',
    'storeid',
    'staffid',
    'saledate',
    'quantity',
    'price',
    'totalsales'
]]

"""Create Time Dimension"""

dim_time = fact_sales[['saledate']].drop_duplicates()
dim_time['year'] = dim_time['saledate'].dt.year
dim_time['month'] = dim_time['saledate'].dt.month
dim_time['day'] = dim_time['saledate'].dt.day

"""Other Dimensions"""

dim_customer = customers
dim_product  = products
dim_store    = stores
dim_staff    = staff

"""# LOAD

Export to CSV
"""

dim_customer.to_csv('dim_customer.csv', index=False)
dim_product.to_csv('dim_product.csv', index=False)
dim_store.to_csv('dim_store.csv', index=False)
dim_staff.to_csv('dim_staff.csv', index=False)
fact_sales.to_csv('fact_sales.csv', index=False)
dim_time.to_csv('dim_time.csv', index=False)

"""Download CSV"""

from google.colab import files

files.download('dim_customer.csv')
files.download('dim_product.csv')
files.download('dim_store.csv')
files.download('dim_staff.csv')
files.download('dim_time.csv')
files.download('fact_sales.csv')